# Generated by Django 4.2 on 2023-04-14 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NewsPortal', '0003_category_subscribers_delete_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='subscribers',
            field=models.ManyToManyField(related_name='author_subs', to=settings.AUTH_USER_MODEL),
        ),
    ]
